apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- github.com/froberge/openshift-catalog/openshift-serverless/operator/overlays/stable?ref=main
# - github.com/froberge/openshift-catalog/openshift-serverless/object/kn-serving/overlays/default?ref=main
